#!/bin/bash

CRONPATH=/var/spool/cron/crontabs/root
BACKUP=`cat ~/crontab_backup`
MDRES=`md5sum /var/spool/cron/crontabs/root | cut -d ' ' -f1`

if [ $BACKUP != $MDRES ]
then
	md5sum $CRONPATH | cut -d ' ' -f1 > ~/crontab_backup
    mail -s "/var/spool/cron/crontabs/root file was modified" root@localhost < $CRONPATH
fi


#edit the crontab (crontab -e) with: 
#0 0 * * 0  sh ~/check_crontab_changes.sh
